//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABORATORIO_CLINICO_LICDA_JIMENEZ_GARRIDO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Usuarios
    {
        public Tipo_Usuarios()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
