//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LABORATORIO_CLINICO_LICDA_JIMENEZ_GARRIDO_ENTITIES : DbContext
    {
        public LABORATORIO_CLINICO_LICDA_JIMENEZ_GARRIDO_ENTITIES()
            : base("name=LABORATORIO_CLINICO_LICDA_JIMENEZ_GARRIDO_ENTITIES")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<KeyValuePair>().HasKey(x => x.Key);
            base.OnModelCreating(modelBuilder, null);
        }
    
        public virtual DbSet<Resultados> Resultados { get; set; }
        public virtual DbSet<Tipo_Resultados> Tipo_Resultados { get; set; }
        public virtual DbSet<Tipo_Usuarios> Tipo_Usuarios { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
