//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultados
    {
        public int Id { get; set; }
        public string Archivo { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_Auxiliar { get; set; }
        public Nullable<System.DateTime> Fecha_Resultados { get; set; }
        public Nullable<int> Tipo_Resultado { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Tipo_Resultados Tipo_Resultados { get; set; }
    }
}
