//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LABORATORIO_CLINICO_LICDA_JIMENEZ_GARRIDO_ENTITIES : DbContext
    {
        public LABORATORIO_CLINICO_LICDA_JIMENEZ_GARRIDO_ENTITIES()
            : base("name=LABORATORIO_CLINICO_LICDA_JIMENEZ_GARRIDO_ENTITIES")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Resultados> Resultados { get; set; }
        public virtual DbSet<Tipo_Resultados> Tipo_Resultados { get; set; }
        public virtual DbSet<Tipo_Usuarios> Tipo_Usuarios { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
